version: "3"
services:
  lab:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kani-lab
    environment:
      - TZ=Asia/Tokyo
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - 8888:8888
    working_dir: /home/jovyan/work
    volumes:
      - ${PWD}:/home/jovyan/work
